### ISSUE TITLE
Use kind-icon only in lsp-mode

### ISSUE THREAD

**Issue by kchousos** [jdtsmith/kind-icon#28]
Hello! Thank you for this great package.

I recently migrated to using corfu instead of company, and everything seems to be working smoothly. My only problem is that I would prefer kind-icons to be used by corfu only in lsp buffers. Is there an easy way to do that?

Thank you in advance.

**Comment by jdtsmith** [comment]
Thanks.  You could make `corfu-margin-formatters` into a buffer-local variable and, presumably in some hook like `lsp-managed-mode-hook`, add `kind-icon-margin-formatter` to it there.  Something like (in a use-package stanza, untested):

```elisp
   :config
   (defun my/enable-kind-icon ()
     (setq-local corfu-margin-formatters '(kind-icon-margin-formatter)))
   :hook  ((lsp-managed-mode . my/enable-kind-icon))
```
 This arranges it so that only in LSP-MODE buffers would `kind-icon-margin-formatter` be on the `corfu-margin-formatters` list.

**Comment by kchousos** [comment]
This does exactly what I need. Thank you very much for your help and quick reply!
