### ISSUE TITLE
Prefix with unknown icon

### ISSUE THREAD

**Issue by TakingWW** [jdtsmith/kind-icon#29]
Unknown icon showing instead of the referred in my config for default kinds.

For `python`  it's type parameter

![PythonUnknown](https://user-images.githubusercontent.com/105567680/216800610-4ad114c1-7b30-4f4e-8c5a-2c3c8aa4f560.png)

For `java` it's enum member

![JvaUnknown](https://user-images.githubusercontent.com/105567680/216801894-06cab7e0-3b07-443e-9270-d654107b02bf.png)

`M-x kind-icon-preview-all` output

![TypeProof](https://user-images.githubusercontent.com/105567680/216801905-db5efeef-61ec-49da-b915-e920dafca311.png)

 - same for enum members (both listed without problems)

I tested others icons which is the same as some working ones and i don't remember messing with something like completion kinds, so i think it's default as shows
``` el
;; Kind Icon Config

(use-package kind-icon
    :ensure t
    :after corfu
    :custom
    (kind-icon-default-face 'corfu-default)
    (package-selected-packages '(kind-icon corfu))
    (kind-icon-blend-background nil)
    (kind-icon-default-style
        '(:padding -0.5 :stroke 0 :margin 0 :radius 0 :height 0.7 :scale 1))
    :config
    (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))

```

I don't know whether they are exclusive of these two languages or not, if someone know any language that could have the same behavior pls tell me so i test.

Observations:

 - Kind Icon version: 0.1.9
 - Emacs version: 28.2
 - let me know if is needed give extra information

**Comment by jdtsmith** [comment]
What is the _source_ of these completions?  

These two kinds have been problematic.  My suspicion is that the `kind` being provided by your completion system is _incorrect_.  The relevant kinds are `enummember`, and `typeparameter` (all one word).  I've seen packages use `enum-member` instead, for example.  Company for example specifies the versions with dashes.  But eglot ~~and lsp-mode both~~ provides the versions _without_ dashes, since that's what the [lsp protocol itself](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentSymbol) specifies.

**Comment by TakingWW** [comment]
> What is the _source_ of these completions?

I'm with `corfu` and `lsp-mode`

For note `lsp-mode` includes dash as words separator (`type-parameter` and `enum-member`) and changing the source solved, more specifically `lsp-completion.el` which list every possible `kind` in `lsp-completion--kind->symbol`

Thanks for the help, appreciate.

**Comment by jdtsmith** [comment]
Thanks for verifying. Sorting it out with the company and lsp-mode maintainers.
