### ISSUE TITLE
Link to nerd-icons-corfu?

### ISSUE THREAD

**Issue by minad** [jdtsmith/kind-icon#39]
Hi JD,

I suggest to add a link to https://github.com/LuigiPiucco/nerd-icons-corfu, which provides similar functionality as your package via Nerd fonts and with other styling. Any maybe remove the links to all-the-icons-completion and nerd-icons-completion? These address minibuffer completion, which is somewhat distinct. Thanks!

Daniel

**Comment by jdtsmith** [comment]
Added.  As mentioned on the nerd-icons README and [the kind-icon wiki](https://github.com/jdtsmith/kind-icon/wiki), this was [already possible](https://github.com/rainstormstudio/nerd-icons.el#use-nerd-icons-with-corfu) quite simply using kind-icon's short-text and `kind-icon-use-icons=nil`.   The one issue with font-based icons (aside from having to install a special font) is they are limited to one character width, vs. 2 for SVG icons.  But of course they do work in the terminal as well (assuming you configure your terminal with a nerd font).

**Comment by minad** [comment]
> As mentioned on the nerd-icons README and the kind-icon wiki, this was already possible quite simply using kind-icon's short-text and kind-icon-use-icons=nil.

Sure, but this is clearly not a good solution. It pulls in svg-lib and kind-icon as unnecessary dependencies without really using them. Compare how simple the nerd-icons-corfu package is: https://github.com/LuigiPiucco/nerd-icons-corfu/blob/master/nerd-icons-corfu.el

I think it would be better if you remove the corresponding configuration from the wiki and not mention this obsolete possibility anymore, since this leads to confusion. Occasionally I remove outdated information from my wikis from time to time, if some feature got upstreamed for instance.

Anyway, I am not an icon user. I am just looking at the various possibilities since they are interesting for Corfu users.

**Comment by jdtsmith** [comment]
> Sure, but this is clearly not a good solution. It pulls in svg-lib and kind-icon as unnecessary dependencies without really using them.

I disagree.  svg-lib is not required, and I don't see how kind-icon could be considered an unnecessary dependency for _itself_.  Very little of kind-icon's code is specific to SVG icon display. For example, it provides more options for foreground/background coloring for whatever icon type you use.  The package you mention is indeed fairly simple,  having apparently distilled the relevant bits from kind-icon.  But in addition to the other features mentioned, kind-icon gives users flexibility to pick and choose among nerd-icons, SVG icons pulled from a half dozen libraries, or simple text markers, on a kind-by-kind basis.

Users may prefer a font-based approach, but again, this is not _a priori_ better: 

1. it depends on an external icon interface package (nerd-icons)
2. you must select and install a nerd-font, and have _permission_ to do so on your system, everywhere you use emacs.  And then of course remember to use that font exclusively.
3. because corfu doesn't have pixel-based alignment, you must stick with a monospace font, which means icons are small (about half the size of kind-icon's), which people complain about.

Other users may prefer the more "full-featured" approach kind-icon provides.  I find users are adept at exploring their options.

**Comment by minad** [comment]
Obviously I agree that fonts are not necessarily better than svgs. My point only applies if users already decided to use nerd-icons for everything. Then using the appropriate nerd-icons-* package is better than the indirection via kind-icon. No intermediate package, configuration is already prepared, etc.

Regarding your points:

1. It is not nice to be tied to a single icon package, however nerd icons already subsume multiple sets. But ideally we would have a single icon-provider package with cl-defgenerics which integrates with every frontend (Corfu, company, minibuffer, dired, ibuffer) and has implementations for various backends (nerd, all the icons, SVG, ...)
2.  Installing fonts is usually possible in the user directory.
3. Yes, of course.
